<?php

########################################################################
# Extension Manager/Repository config file for ext: "jw_forms"
#
# Auto generated by Extension Builder 2013-11-12
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = [
    'title' => 'JW Forms',
    'description' => 'This extension gives you the possibility to display title and file ' .
        'of forms (PDF, ...) by starting letter and search forms of this list.',
    'category' => 'plugin',
    'author' => 'Stefan Froemken',
    'author_email' => 'sfroemken@jweiland.net',
    'author_company' => 'jweiland.net',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.6.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
